package com.guardianxr.ar;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;
public class AssessmentActivity extends Activity{SharedPreferences p;LinearLayout box;int score=0,q=0;String module;
 @Override protected void attachBaseContext(Context n){super.attachBaseContext(LocaleUtil.apply(n));}
 int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("guardianxr",MODE_PRIVATE);module=getIntent().getStringExtra("module");if(module==null)module="FIRE";showQ();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(dp(12),dp(12),dp(12),dp(12));return v;}
 void base(){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(24),dp(42),dp(24),dp(24));box.setBackgroundColor(0xff07101c);setContentView(box);}
 String[][] data(){return module.equals("GAS")?new String[][]{{getString(R.string.gq1),getString(R.string.ga11),getString(R.string.ga12),getString(R.string.ga13),getString(R.string.ga11)},{getString(R.string.gq2),getString(R.string.ga21),getString(R.string.ga22),getString(R.string.ga23),getString(R.string.ga21)},{getString(R.string.gq3),getString(R.string.ga31),getString(R.string.ga32),getString(R.string.ga33),getString(R.string.ga31)}}:new String[][]{{getString(R.string.fq1),getString(R.string.fa11),getString(R.string.fa12),getString(R.string.fa13),getString(R.string.fa11)},{getString(R.string.fq2),getString(R.string.fa21),getString(R.string.fa22),getString(R.string.fa23),getString(R.string.fa21)},{getString(R.string.fq3),getString(R.string.fa31),getString(R.string.fa32),getString(R.string.fa33),getString(R.string.fa31)}};}
 void showQ(){base();String[][] a=data();if(q>=a.length){finishTest(a.length);return;}TextView h=t("GuardianXR • "+getString(R.string.assessment),20);h.setTypeface(null,1);box.addView(h);box.addView(t((q+1)+"/"+a.length+"  "+a[q][0],18));for(int i=1;i<=3;i++){Button x=new Button(this);x.setAllCaps(false);x.setText(a[q][i]);x.setTextSize(15);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58));lp.setMargins(0,dp(6),0,dp(6));x.setLayoutParams(lp);final String ans=a[q][i],correct=a[q][4];x.setOnClickListener(v->{if(ans.equals(correct))score++;q++;showQ();});box.addView(x);}}
 void finishTest(int total){base();int pct=score*100/total;boolean pass=pct>=67;p.edit().putInt(module+"_score",pct).putBoolean(module+"_passed",pass).apply();box.addView(t((pass?getString(R.string.passed):getString(R.string.retry_required))+" • "+pct+"%",24));box.addView(t(pass?getString(R.string.assessment_verified):getString(R.string.score_requirement),17));Button c=new Button(this);c.setText(pass?getString(R.string.generate_certificate):getString(R.string.back_training));c.setOnClickListener(v->{if(pass){Intent i=new Intent(this,CertificateActivity.class);i.putExtra("module",module);startActivity(i);}finish();});box.addView(c);}}
