package com.guardianxr.ar;

import android.Manifest; import android.app.Activity; import android.content.Intent; import android.content.SharedPreferences; import android.content.pm.PackageManager; import android.graphics.Color; import android.graphics.PointF; import android.graphics.drawable.GradientDrawable; import android.opengl.GLES20; import android.opengl.GLSurfaceView; import android.os.Bundle; import android.view.Gravity; import android.view.MotionEvent; import android.view.View; import android.widget.*; import com.google.ar.core.*; import java.util.concurrent.atomic.AtomicReference;

public class MainActivity extends Activity implements GLSurfaceView.Renderer {
  private GLSurfaceView gl; private Session session; private TextView badge,title,task,progress; private Button fire,gas,action,reset; private String mode="FIRE"; private int step=0; private Anchor anchor; private final AtomicReference<PointF> pendingTap=new AtomicReference<>(); private final BackgroundRenderer background=new BackgroundRenderer(); private final HazardRenderer hazard=new HazardRenderer(); private final float[] proj=new float[16],view=new float[16];
  private SharedPreferences prefs; private int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int color,float r){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(r));return d;} private GradientDrawable stroke(int fill,int line,float r){GradientDrawable d=bg(fill,r);d.setStroke(dp(1),line);return d;}
  private TextView text(String s,float size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
  private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setPadding(dp(10),0,dp(10),0);return b;}
  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("guardianxr",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(7,12,22));getWindow().setNavigationBarColor(Color.rgb(7,12,22));
    FrameLayout root=new FrameLayout(this); gl=new GLSurfaceView(this);gl.setEGLContextClientVersion(2);gl.setRenderer(this);gl.setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);root.addView(gl,new FrameLayout.LayoutParams(-1,-1));
    LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(16),dp(14),dp(16),dp(14));top.setBackground(bg(0xE6121928,0));
    LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL); TextView shield=text("◆",22,0xFF59D9FF);brand.addView(shield); LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.setPadding(dp(10),0,0,0); title=text("GuardianXR",21,Color.WHITE);title.setTypeface(null,1);names.addView(title);TextView sub=text("SPATIAL SAFETY TRAINING",10,0xFF9EACC2);names.addView(sub);brand.addView(names,new LinearLayout.LayoutParams(0,-2,1)); badge=text("● AR LIVE",11,0xFF78F0B3);badge.setPadding(dp(10),dp(6),dp(10),dp(6));badge.setBackground(stroke(0x3323C483,0xFF2CD89B,20));brand.addView(badge);top.addView(brand);
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(stroke(0xE61A2436,0xFF33445F,14));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(12),0,0);top.addView(card,cp); progress=text("FIRE  •  STEP 0 OF 3",11,0xFFFFA45C);progress.setTypeface(null,1);card.addView(progress);task=text("Scan a surface and tap to place the fire hazard.",15,Color.WHITE);task.setPadding(0,dp(5),0,0);card.addView(task);
    root.addView(top,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));
    LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);controls.setPadding(dp(10),dp(9),dp(10),dp(12));controls.setBackground(bg(0xED0D1422,18));fire=button("🔥  Fire");gas=button("☁  Gas");action=button("✓  Complete");reset=button("↻");controls.addView(fire,new LinearLayout.LayoutParams(0,dp(50),1));controls.addView(gas,new LinearLayout.LayoutParams(0,dp(50),1));controls.addView(action,new LinearLayout.LayoutParams(0,dp(50),1.35f));controls.addView(reset,new LinearLayout.LayoutParams(dp(52),dp(50)));FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);bp.setMargins(dp(10),0,dp(10),dp(10));root.addView(controls,bp);setContentView(root);
    fire.setOnClickListener(v->switchMode("FIRE"));gas.setOnClickListener(v->switchMode("GAS"));reset.setOnClickListener(v->switchMode(mode));action.setOnClickListener(v->{if(step==3){prefs.edit().putBoolean(mode+"_training_complete",true).apply();Intent i=new Intent(this,AssessmentActivity.class);i.putExtra("module",mode);startActivity(i);return;}if(anchor==null){task.setText("Move slowly, scan a textured floor/wall, then tap to place the hazard.");return;}step=Math.min(3,step+1);updateTask();});gl.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP)pendingTap.set(new PointF(e.getX(),e.getY()));return true;});updateTask();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},7);
  }
  private void switchMode(String m){mode=m;step=0;if(anchor!=null){anchor.detach();anchor=null;}updateTask();}
  private void updateTask(){String[] f={"Scan a surface and tap to place the fire hazard.","Choose a safe approach and extinguisher procedure.","Confirm alarm and evacuation route.","Fire & Explosion module complete — response sequence verified."};String[] g={"Scan a surface and tap to place the gas-leak hazard.","Establish exclusion zone + PPE / buddy check.","Confirm ventilation and escape route.","Gas Leak & Confined Space module complete — response sequence verified."};task.setText((mode.equals("FIRE")?f:g)[Math.min(step,3)]);progress.setText(mode+"  •  STEP "+step+" OF 3");int accent=mode.equals("FIRE")?0xFFFF8A45:0xFF52E6B8;progress.setTextColor(accent);fire.setBackground(stroke(mode.equals("FIRE")?0x55FF6B35:0x331E293B,mode.equals("FIRE")?0xFFFF7A3D:0xFF3B4B64,14));gas.setBackground(stroke(mode.equals("GAS")?0x5540DDA8:0x331E293B,mode.equals("GAS")?0xFF45E2B1:0xFF3B4B64,14));action.setBackground(bg(step==3?0xFF167A5A:0xFF246BFD,14));reset.setBackground(stroke(0x331E293B,0xFF3B4B64,14));if(step==3){action.setText("Start Assessment");}else action.setText("✓  Complete");}
  @Override public void onResume(){super.onResume();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)return;try{if(session==null){if(ArCoreApk.getInstance().requestInstall(this,true)==ArCoreApk.InstallStatus.INSTALL_REQUESTED)return;session=new Session(this);Config c=new Config(session);c.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL_AND_VERTICAL);c.setInstantPlacementMode(Config.InstantPlacementMode.LOCAL_Y_UP);session.configure(c);}session.resume();gl.onResume();}catch(Exception e){task.setText("AR unavailable: "+e.getClass().getSimpleName());}}
  @Override public void onPause(){super.onPause();gl.onPause();if(session!=null)session.pause();}
  @Override public void onSurfaceCreated(javax.microedition.khronos.opengles.GL10 g,javax.microedition.khronos.egl.EGLConfig c){GLES20.glClearColor(.03f,.04f,.06f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);background.create();hazard.create();}
  @Override public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);if(session!=null)session.setDisplayGeometry(getWindowManager().getDefaultDisplay().getRotation(),w,h);}
  @Override public void onDrawFrame(javax.microedition.khronos.opengles.GL10 g){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);if(session==null)return;try{session.setCameraTextureName(background.textureId());int gw=gl.getWidth(),gh=gl.getHeight();if(gw>0&&gh>0)session.setDisplayGeometry(getWindowManager().getDefaultDisplay().getRotation(),gw,gh);Frame frame=session.update();background.draw(frame);PointF tap=pendingTap.getAndSet(null);if(tap!=null)handleTap(frame,tap.x,tap.y);Camera cam=frame.getCamera();if(cam.getTrackingState()!=TrackingState.TRACKING)return;cam.getProjectionMatrix(proj,0,.1f,100f);cam.getViewMatrix(view,0);if(anchor!=null&&anchor.getTrackingState()==TrackingState.TRACKING)hazard.draw(anchor.getPose(),view,proj,mode.equals("FIRE"));}catch(Exception e){runOnUiThread(()->task.setText("AR frame error: "+e.getClass().getSimpleName()));}}
  private void handleTap(Frame frame,float x,float y){if(anchor!=null||frame.getCamera().getTrackingState()!=TrackingState.TRACKING)return;for(HitResult hit:frame.hitTest(x,y)){Trackable t=hit.getTrackable();boolean plane=t instanceof Plane&&((Plane)t).isPoseInPolygon(hit.getHitPose());boolean point=t instanceof Point&&((Point)t).getOrientationMode()==Point.OrientationMode.ESTIMATED_SURFACE_NORMAL;if(plane||point){placeAnchor(hit);return;}}for(HitResult hit:frame.hitTestInstantPlacement(x,y,1.0f)){if(hit.getTrackable() instanceof InstantPlacementPoint){placeAnchor(hit);return;}}runOnUiThread(()->task.setText("Move slowly, scan a textured floor/wall, then tap again."));}
  private void placeAnchor(HitResult hit){anchor=hit.createAnchor();step=1;runOnUiThread(this::updateTask);}
}
