package com.guardianxr.ar;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;
public class RecordsActivity extends Activity{
 int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);v.setPadding(0,dp(5),0,dp(5));return v;}
 @Override protected void attachBaseContext(Context n){super.attachBaseContext(LocaleUtil.apply(n));}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff06101d);getWindow().setNavigationBarColor(0xff06101d);SharedPreferences p=getSharedPreferences("guardianxr",MODE_PRIVATE);String view=getIntent().getStringExtra("view");if(view==null)view="modules";int fs=p.getInt("FIRE_score",0),gs=p.getInt("GAS_score",0);boolean fp=p.getBoolean("FIRE_passed",false),gp=p.getBoolean("GAS_passed",false);String cert=p.getString("last_cert","");
 ScrollView sv=new ScrollView(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(24),dp(28),dp(24),dp(28));l.setBackgroundColor(0xff06101d);sv.addView(l);l.addView(t("GuardianXR",28,Color.WHITE,true));l.addView(t(getString(R.string.record_verification),14,0xff8dc9ff,true));
 if(view.equals("modules")){l.addView(t(getString(R.string.module_records),22,Color.WHITE,true));module(l,"🔥  "+getString(R.string.fire_module_title),fp,fs);module(l,"☁  "+getString(R.string.gas_module_title),gp,gs);}
 else if(view.equals("scores")){l.addView(t(getString(R.string.score_records),22,Color.WHITE,true));score(l,getString(R.string.fire_assessment),fs,fp);score(l,getString(R.string.gas_assessment),gs,gp);int count=(fp?1:0)+(gp?1:0);int avg=count==0?0:((fp?fs:0)+(gp?gs:0))/count;l.addView(t(getString(R.string.verified_average)+": "+avg+"%",20,0xffff7438,true));}
 else {l.addView(t(getString(R.string.certificate_records),22,Color.WHITE,true));if(cert.isEmpty())l.addView(t(getString(R.string.no_certificate_record),16,0xff9fb0c8,false));else {String data=p.getString("cert_"+cert,null);boolean ok=data!=null&&data.contains("GUARDIANXR|")&&data.contains("|PASSED|");l.addView(t(getString(R.string.certificate_id)+": "+cert,17,Color.WHITE,true));l.addView(t(ok?getString(R.string.verified)+" ✓":getString(R.string.not_verified),18,ok?0xff38e6ae:0xffff7438,true));if(data!=null)l.addView(t(data,12,0xff9fb0c8,false));Button v=new Button(this);v.setText(R.string.verify_certificate);v.setOnClickListener(x->{Intent i=new Intent(this,VerifyActivity.class);i.putExtra("cert_id",cert);startActivity(i);});l.addView(v);}}
 setContentView(sv);}
 void module(LinearLayout l,String name,boolean passed,int score){l.addView(t(name,19,Color.WHITE,true));l.addView(t((passed?getString(R.string.verified):getString(R.string.pending))+" • "+score+"%",15,passed?0xff38e6ae:0xff9fb0c8,true));}
 void score(LinearLayout l,String name,int score,boolean passed){l.addView(t(name+": "+score+"%",18,Color.WHITE,true));l.addView(t(passed?getString(R.string.passed)+" ✓":getString(R.string.pending),14,passed?0xff38e6ae:0xff9fb0c8,false));}
}